TELEGRAM_BOT_TOKEN=''

MENU, WEATHER, ANALIZE_CONVERSATION, CLOTH_RECOMENDATIONS, RESUME_OPTIONS_MENU, RESUME_AUDIO, RESUME_PDF, RESUME_FORMAT = range(8)
MAX_MESSAGE_LENGTH= 4096
MAX_CLOTH_GENERATION_USES= 2
OPENWEATHER_API_KEY=''

MAGICLOOP_WEATHER_FUNCTION_KEY=''

OPENAI_API_KEY=''
DEVELOPER_CHAT_ID=''
from settings_local import *